# Generated by Django 3.2.13 on 2022-05-14 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(verbose_name='最近修改时间')),
                ('body', models.TextField(verbose_name='正文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_time', 'title'],
            },
        ),
    ]
