# Generated by Django 3.2.13 on 2022-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name2',
            field=models.CharField(choices=[(1, '维护'), (2, '测试'), (3, '其他')], default='其他', max_length=30, verbose_name='类别'),
        ),
    ]
