# Generated by Django 3.2.13 on 2022-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20220515_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, '维护'), (2, '测试'), (3, '节日'), (4, '招募'), (5, '其他')], default=(3, '节日'), max_length=30, verbose_name='类别'),
        ),
    ]
