# Generated by Django 3.2.13 on 2022-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[(1, '维护'), (2, '测试'), (3, '节日'), (4, '招募'), (5, '其他')], max_length=30, verbose_name='分类'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
