# Generated by Django 3.2.13 on 2022-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20220515_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('维护', '维护'), ('测试', '测试'), ('节日', '节日'), ('招募', '招募'), ('其他', '其他')], max_length=30, verbose_name='分类'),
        ),
    ]
